### ISSUE TITLE
Problem with Unbury

### ISSUE THREAD

**Issue by Pet20q** [ijgnd/anki__reviewer_selective_bury_and_unbury__postpone_card_for_later#1]
Hello!
For some reason when I Unbury my cards (alt+z) it resets every card that is in "Learning" stage in every deck so my entire profile resets.
I tried to disable every other addon but it didn't help and I tried to downgrade my anki to 2.1.7
Learning cards still reset when I press Unbury

**Comment by ijgnd** [comment]
Thanks for this report. It's really good that you spotted this problem. 

short version: download the latest version from [ankiweb](https://ankiweb.net/shared/info/1513254129) and try again. Does this solve your problem?

details:  

I test with the latest anki version which is 2.1.15 and the scheduler v1.

This problem should occur if you run the built-in method `buryCards` from the Scheduler class with an empty list (even if you don't use any add-ons). You can check if this also happens for you by executing `aqt.mw.col.sched.buryCards([])` from the debug console, https://apps.ankiweb.net/docs/manual.html#debug-console

I didn't spot this problem because I assumed that passing an empty list to the built-in method `buryCards` would do nothing and I didn't encounter this bug because for many decks I enable burying of siblings so that I virtually always have some buried cards when I run the command "limited unbury" from my add-on.

**Comment by Pet20q** [comment]
Everything works now pefrectly! (2.1.15ver)
I'll let you know If something happens again 
Thank you!
